repositoryUrl: https://github.com/getappmap/appmap-node.git
tagFormat: v${version}
dryRun: false
ci: true
branches:
  - name: main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/npm"
  - "@semantic-release/git"
  - "@semantic-release/github"
